### ISSUE TITLE
Please, update the runtime to org.gnome.Platform 3.34

### ISSUE THREAD

**Issue by codingepaduli** [flathub/org.remmina.Remmina#10]
Please, 

can you update the runtime to org.gnome.Platform 3.34 ?

**Comment by larchunix** [comment]
Hi,

I have a branch ready with GNOME 3.34 however I'm waiting for https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886 to be fixed before pushing it.

**Comment by go-ten** [comment]
Hi,

if I'm not mistaken, it's fixed since version 1.4.3 and version 1.2.5 (Debian Stable for example).

[https://github.com/flatpak/flatpak/issues/3126](url)

**Comment by larchunix** [comment]
> if I'm not mistaken, it's fixed since version 1.4.3 and version 1.2.5 (Debian Stable for example).
> 
> [https://github.com/flatpak/flatpak/issues/3126](url)

Those are different issues.

flatpak (I'm using 1.5.0) still fails to install org.freedesktop.Platform.openh264 if  org.freedesktop.Platform is not installed.

**Comment by antenore** [comment]
@larchunix We have just release the v1.3.7 I let you decide what is better to do, waiting for 3.34 or release ASAP the stable flatpak with the latest tag.

Thanks!!!

**Comment by larchunix** [comment]
@antenore I pushed new flatpak version with gnome sdk 3.34 and remmina 1.3.7. freerdp h264 users have to manually install org.freedesktop.Platform in order to be able to install org.freedesktop.Platform.openh264 and having support for this codec.

**Comment by antenore** [comment]
@larchunix thank you!

Cc: @giox069
