### ISSUE TITLE
Remmina does not show any saved profiles since update to 1.4.22

### ISSUE THREAD

**Issue by okkiv** [flathub/org.remmina.Remmina#108]
Hi,

I'm sorry, if this is a duplicate but I could not find a ticket related to my problem neither here nor in remmina's gitlab repo.

Since the update to version 1.4.22 last saturday, remmina does not show my previously created profiles.
The profile files do still exist under /home/$USER/.var/app/org.remmina.Remmina/data/remmina, though.
When I add a new profile, it is not written to that folder and upon restart it is forgotten about.

I have installed Remmina with ``--user`` on fedora 35.

Please let me know if you need any more details.

Best regards
Viktor

**Comment by antenore** [comment]
Open three remmina preferences and check that the profile path is correctly set.

If not, backup your profiles and reinstall remmina. Looks like a flatpak issue

**Comment by okkiv** [comment]
Have tried and succeeded, thanks alot!
It was showing ``remmina`` in the drop down, so I navigated to the correct folder. Afterwards it just showed ``remmina`` again.
On restart it picked up my profiles.
