### ISSUE TITLE
bugreport: Cannot disable shared folder for RDP connections using the GUI in Remmina 1.4.23

### ISSUE THREAD

**Issue by Lalarian** [flathub/org.remmina.Remmina#112]
Hello!
I once had the shared folder enabled for one of my RDP connections. Now I wanted to disable the shared folder completely.
But when I uncheck 'Shared folder" and save, the connection will remain configured with shared folder enabled.
Other configuration options like color depth and network type are saved fine.
I disabled the shared folder editing the configuration file with nano and this also disabled the feature in the GUI.
After enabling and saving shared folder in the GUI, it again became impossible to disable.

**Comment by antenore** [comment]
WOW! Never realized this, thanks for reporting.
Am I asking you too much to report this upstream?

https://gitlab.com/Remmina/Remmina/-/issues 

Thanks!

**Comment by Lalarian** [comment]
> WOW! Never realized this, thanks for reporting. Am I asking you too much to report this upstream?
Well, probably not .. I will try my best xD

I just often don't know exactly where the bug reports belong.

Thank you for replying!

**Comment by Lalarian** [comment]
So I did: https://gitlab.com/Remmina/Remmina/-/issues/2679
