### ISSUE TITLE
Enable voluntarily telemetry

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.remmina.Remmina#12]
Could you please enable the voluntarily telemetry on compile time. Right now, it is disabled in the Flatpak which means that the official data does not properly reflect the user base:

https://remmina.org/remmina-stats/

I totally agree that any kind of telemetry should only be opt in. The amount of companies that disrespect their users (and/or local laws) with opt-out telemetry is disgraceful, but Remmina is not a part of that.

![Screenshot from 2019-12-09 08-57-53](https://user-images.githubusercontent.com/33983090/70417741-2cdcb380-1a62-11ea-9c9f-c6520bc7c4f0.png)

**Comment by antenore** [comment]
I'm not sure I've understood, do you mean the "Send anonymous statistics...." cannot be enabled with the flatpak? Or that it should be ON by default?

If it's the second case, well, we would love it, actually there are only 100k users that opted-in, imagine what are the real numbers (we estimated that only 10 to 15 % enable it), but even if we don't collect sensible data and we are not so good at parsing the numbers, people must not be forced. 
 
It'd nice to find a way to convince more people…

**Comment by Eonfge** [comment]
I was triggered by the line `"-DWITH_TELEPATHY:BOOL=OFF"` in the manifest. Does this mean that the telemetry switch doesn't work?

Perhaps I understand the situation wrong, but I'm all in favour of opt-in statistics. I'm under the impression that with the line in the manifest, there is no analytics collection at all. I this a correct assumption, or am I missing the forest for the trees?

**Comment by antenore** [comment]
That is an unmaintained plugin that we have disabled. It was used with VNC

**Comment by antenore** [comment]
For posterity https://developer.gnome.org/platform-overview/unstable/tech-telepathy.html.en

**Comment by Eonfge** [comment]
Aaaaaah. Never mind then :+1:
