### ISSUE TITLE
Dark icon toggle does not work

### ISSUE THREAD

**Issue by jtagcat** [flathub/org.remmina.Remmina#14]
![Screenshot from 2019-12-17 12-03-23](https://user-images.githubusercontent.com/38327267/70985755-8cffd500-20b4-11ea-8508-f25ae0d4830b.png)
Flatpak Remmina always displays the dark icon (independent of the `Dark Tray icon` toggle under Preferences -> Applet).
Installing from other sources it works properly.

**Comment by antenore** [comment]
[This commit](https://gitlab.com/Remmina/Remmina/commit/bb7d3cf9a1c360c9d0505f407a0f51159924e516#a355a6a84541b17c96b7f474c79c6496633711ae_81_82) should have fixed this issue, but I'm not sure.

Let's keep this issue updated as soon as the v1.3.8 will be released

**Comment by luni3359** [comment]
I'm not sure if this falls into the same issue, but I can't see the tray icon no matter what. It's empty, but still usable.

**Comment by Hannes1909** [comment]
Same here, installed 1.4.11 flatpak release today:
![image](https://user-images.githubusercontent.com/29476657/108602490-73d27280-73a2-11eb-94dc-e4a136ad9558.png)

**Comment by luni3359** [comment]
Yeah, I don't think it's showing up in either dark or light modes

**Comment by antenore** [comment]
It works for me.

This is not a Remmina specific issue, but it's more related to the windows manager and used theme.

Probably installing a flatpak theme may help, but I'm not sure, on my side I've installed `org.gtk.Gtk3theme.Breeze-Dark`

My understanding is that you have to match dark/light theme on flatpak.

In some days I'll release a new Remmina version that doesn't use anymore these icons, but will use directly the dark/white window manager theme, hopefully this should really help.

I'll close this as it's really not a Remmina problem.

@luni3359 @Hannes1909

**Comment by luni3359** [comment]
Thank you, I hope it works. Also, just to give some information on my system: On a fresh KDE Neon install, Remmina has no icons on the bar.
