### ISSUE TITLE
Latest flatpak build fails to run

### ISSUE THREAD

**Issue by k4n30** [flathub/org.remmina.Remmina#147]
As title suggests.

flatpak run org.remmina.Remmina

remmina-Message: 12:49:35.372: Remmina does not log all output statements. Turn on more verbose output by using "G_MESSAGES_DEBUG=all" as an environment variable.
More info available on the Remmina wiki at:
https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-debugging
Load modules from /app/lib/remmina/plugins
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.

(process:3): libsoup-ERROR **: 12:49:35.723: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.

#145

**Comment by usrstephan** [comment]
same problem for me
ubuntu 22.04, wayland (default), remmina update today, also after reboot:

remmina-Message: 08:32:20.109: Remmina does not log all output statements. Turn on more verbose output by using "G_MESSAGES_DEBUG=all" as an environment variable.
More info available on the Remmina wiki at:
https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-debugging
Load modules from /app/lib/remmina/plugins
xprop:  unable to open display ''
xprop:  unable to open display ''

(process:2): libsoup-ERROR **: 08:32:20.212: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.

**Comment by neildarlow** [comment]
Same error as @k4n30 on fedora Silverblue 36 i.e. glibsecret and libsoup.

`remmina-Message: 08:36:03.660: Remmina does not log all output statements. Turn on more verbose output by using "G_MESSAGES_DEBUG=all" as an environment variable.
More info available on the Remmina wiki at:
https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-debugging
Load modules from /app/lib/remmina/plugins
xprop:  unable to open display ''
xprop:  unable to open display ''
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.

(process:2): libsoup-ERROR **: 08:36:03.795: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.`

**Comment by antenore** [comment]
A

**Comment by FelixSchwarz** [comment]
just a quick note on how to downgrade remmina in case someone needs a working (albeit older) remmina right now:

    $ flatpak remote-info --log flathub
    # in my case the previous commit is 8c3415b6 ("Removing patch (0f127f25)", 2022-06-20)
    $ flatpak update --commit=8c3415b68da071652914ed17cabf72d4aea1b8e41541618b2d7972bc0f3fa35d org.remmina.Remmina

**Comment by antenore** [comment]
A new flatpak is going to be published. Thanks @Eonfge for the quick fix, it's much appreciated

**Comment by Eonfge** [comment]
@antenore Time to close this issue?

**Comment by neildarlow** [comment]
Fixed for me. Currently running 1.4.27 from flatpak.

**Comment by antenore** [comment]
Yes! Thanks again @Eonfge and @neildarlow for confirmation
