### ISSUE TITLE
explicitly add runtime extension for openh264

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/org.remmina.Remmina#15]
As I undestand org.freedesktop.Platform.openh264 is an optional dependency for Remmina.
I do not have org.freedesktop.Platform.openh264 inststalled by default as it often causes problems.

Maybe add org.freedesktop.Platform.openh264 to the runtime extensions so it shows when installing?

**Comment by larchunix** [comment]
org.freedesktop.Platform.openh264 is already a dependency of org.gnome.Platform required by Remmina (https://gitlab.gnome.org/GNOME/gnome-build-meta/blob/gnome-3-34/elements/flatpak/platform.bst#L82-86).

It will be installed automatically once https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886 is fixed.
