### ISSUE TITLE
Remmina crashes on Fedora 37 after closing arbitrary connection 

### ISSUE THREAD

**Issue by Mormacill** [flathub/org.remmina.Remmina#163]
After closing any connection like ssh or rdp in Remmina on Fedora 37, the window freezes for a second, then crashes including the main connection selection window.
I reproduced it in a virtual maschine (install Fedora 37 Workstation, install repofile for flathub, install Remmina): 
[1.webm](https://user-images.githubusercontent.com/31103546/207080892-7b1cc9a3-60ad-4ba5-ad54-0a84f6e01043.webm)

Output log with verbose flag:
[remminaLog.txt](https://github.com/flathub/org.remmina.Remmina/files/10209289/remminaLog.txt)

**Comment by zocker-160** [comment]
known bug in remmina, see https://gitlab.com/Remmina/Remmina/-/issues/2832

**Comment by Mormacill** [comment]
Solved with release [v1.4.29](https://gitlab.com/Remmina/Remmina/-/releases/v1.4.29)
