### ISSUE TITLE
Remmina permissions on last update (1.4.11)

### ISSUE THREAD

**Issue by Taulim** [flathub/org.remmina.Remmina#43]
First of all, thank you for you work on supporting Remmina for flatpak.

It was a long time since I last updated my flatpaks and did it today.
Remmina had a change on permissions from **home** to **host** file system (#40).

I simply cannot find the reason for this change and don't feel comfortable at all with the change (without a reason of course).
However you may have a reason for that that is not written anywhere... =/

For now I just reverted it using flatseal and everything seems to still work as expected.

Thank you!

**Comment by antenore** [comment]
Thanks for your kindness

I had two different issues:

1. Some users reported issues sharing the audio with pulseaudio.
2. My profiles are stored outside the zone accessible by the flatpak

For the first point I cannot reproduce the issue my self, but in both cases changing the permissions from home to host seems to solve the problem.

Regarding the profiles placement (outside the home directory), I don't see a flexible way to solve it, but for the audio may be yes.

Do you have any ideas about both? I can switch back to *home* in any moment BTW and see what happens

**Comment by Taulim** [comment]
Thanks for the quick answer.

1. I just did a test here connecting to a windows 10 machine via RDP and the audio works fine even without the system filesystem (I actually removed even the home folder and left only `xdg-public-share` folder access).
We probably need more information from the issue.

2. Since the system will map "~" to the users home folder set on the `/etc/passwd` file (in which case the `home` filesystem would work) I'm assuming that your profile is attached to the user in another way.
In this case I think the *override* files are a better option for non-standard setups (same files changed by the Flatseal application).

I'm not expert on either Flatpak or Linux, but changing the file system to host seems a bit of a stretch :)

**Comment by antenore** [comment]
It was a desperate attempt 😃

I'll revert and do some tests

Thanks!

**Comment by antenore** [comment]
Done, just wait for the build to finish

**Comment by Taulim** [comment]
Thanks for listening!
I was expecting this on the next Remmina update :smile: .
Already got the update here. Thank you!

**Comment by antenore** [comment]
Security has an higher priority ;-)
