### ISSUE TITLE
SPICE Plugin

### ISSUE THREAD

**Issue by pick2510** [flathub/org.remmina.Remmina#44]
It seems the SPICE Plugin is missing in the last build.

`Remmina - Remote Desktop Client

          ID: org.remmina.Remmina
         Ref: app/org.remmina.Remmina/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.11
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 14.8 MB
     Runtime: org.gnome.Platform/x86_64/3.38
         Sdk: org.gnome.Sdk/x86_64/3.38

      Commit: 3ca043f40e97fabd57419e80effe6cf77b3cb038e44c6c63bfd649f9f2fbd076
      Parent: c1724e7bffbdbbc96c9240686f556af03f622df68f3badcb778c3a4aa5c0e82b
     Subject: Set file system permission confined to home (3906312e)
        Date: 2021-02-04 09:23:38 +0000
`

If I want to connect to SPICE hosts, Remmina say to install the SPICE plugin first.

**Comment by antenore** [comment]
Thanks for the report, I'm investigating

**Comment by antenore** [comment]
We have introduced a new feature that uses a new spice function `spice_display_channel_change_preferred_video_codec_types`

I'm checking if and how to update the spice provided by the flatpak

**Comment by pick2510** [comment]
Thank's for taking care.

**Comment by antenore** [comment]
The updated flatpak will be available in some minutes

**Comment by antenore** [comment]
@pick2510 can you confirm if it works now?

Thanks!

**Comment by pick2510** [comment]
Sorry, all works now. Thanks!
