### ISSUE TITLE
Upgrade to GNOME (platform/sdk) 40 whenever possible

### ISSUE THREAD

**Issue by x80486** [flathub/org.remmina.Remmina#62]

**Comment by codingepaduli** [comment]
org.remmina.Remmina is stuck to org.gnome.Platform/x86_64/3.38

Can it be upgraded to org.gnome.Platform/x86_64/3.40, please?

**Comment by antenore** [comment]
I'll do it ASAP @codingepaduli

**Comment by antenore** [comment]
I misunderstood the issue, sorry.

Remmina cannot be upgraded to that SDK I'm afraid as the code need huge rewrite to work with Gtk4.

@x80486 @codingepaduli is this what you are asking for?

**Comment by antenore** [comment]
Done, looks good.

I thought GNOME 40 wasn't including Gtk3
