### ISSUE TITLE
Flameshot Tray Icon Not Visible

### ISSUE THREAD

**Issue by ProfessorCode212** [flathub/org.remmina.Remmina#84]
On Linux Mint 20, this is what the tray icon for _Remmina_ looks like.

![image](https://user-images.githubusercontent.com/78950242/136506778-b48ca9e8-0435-430b-bd79-b2505a38c767.png)

I presume what should be shown is the logo and not that.

**Comment by eduardosm** [comment]
This bug can also be reproduced on GNOME with the appindicator extension. Instead of the application icon, it shows three dots (···).

**Comment by ProfessorCode212** [comment]
@antenore I am using the default appindicator and it appears to be updated.

**Comment by antenore** [comment]
Yes @eduardosm , normally I've at least 3 different remmina version installed

**Comment by eduardosm** [comment]
It seems that the indicator is set to use the `/usr/share/icons/hicolor/*/status/remmina-status` icon, which flatpak is not exporting, so the icon will only appear if there is non-flatpak version providing such icon.

**Comment by eduardosm** [comment]
It looks like flatpak only exports icons with certain names (https://github.com/flatpak/flatpak/issues/4495#issuecomment-945138992), so I think the easiest solution is to rename the icon.

**Comment by antenore** [comment]
@ProfessorCode212 @eduardosm 

Can you kindly test this flatpak https://remmina.org/public/packages/remmina-dev.flatpak

Thanks in advance

**Comment by ProfessorCode212** [comment]
@antenore I can also confirm that it's working on Linux Mint (Cinnamon). Thanks!

![image](https://user-images.githubusercontent.com/78950242/137821775-e96ca896-708e-4024-a68a-19d6b0ad81ed.png)

**Comment by DANW999** [comment]
I used Budgie 21.10 and still have this same problem, the icon for Flatpak version of Remmina does not load in the system tray, instead it shows a stop sign. How do I go about resolving this please?
