### ISSUE TITLE
multi password changer is not work

### ISSUE THREAD

**Issue by avlubimov** [flathub/org.remmina.Remmina#9]
The multi password function does not work.

In the logs he writes that he cannot connect to the password service.

"WARNING: Remmina is running with a secret plugin, but it cannot connect to a secret service."

As far as I know, remmina uses the gnome-keyring service.

But the seahorse application from the distribution and even the same application from flathub work fine. What could be the problem?

![изображение](https://user-images.githubusercontent.com/622842/61184577-1881bf80-a658-11e9-81f4-b4be545ca30c.png)

**Comment by avlubimov** [comment]
Everything is working.
But remmina requires that a password container be created in the seahorse application before and this container should be set as default.

![изображение](https://user-images.githubusercontent.com/622842/61185305-5f73b300-a660-11e9-93de-41b2a4c02c1e.png)

**Comment by giox069** [comment]
Thank you.
PS: Please, next time open an issue on gitlab. We moved on gitlab, and maybe our flatpack maintanier is not reading these messages here.
